name: Build

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install qt5-default libqt5charts5-dev -y

      - name: Build
        run: |
          cd QMM
          qmake
          make
